// Shared FAQ copy: rendered on the landing page and emitted as FAQPage JSON-LD.
export const FAQ: [string, string][] = [
  ['What Is A Credit?','One credit runs a design, restyle, virtual stage, declutter, material swap, sky swap or style transfer. A scope and budget from your photo is 3 credits, a 2D to 3D floor plan is 6 and a video walkthrough is 40. One balance, no second number to track. Credits reset monthly and never expire while your subscription is active.'],
  ['How Accurate Is The Cost Estimate?','It is a planning estimate, not a construction bid. The engine reads the design it produced, converts it into line items with quantities, and prices those against labor and material rates for your market. We show it as a range with a confidence level rather than a single fake number, because anything more precise than that would be dishonest. Investors use it to underwrite and contractors use it as a starting proposal. Your subcontractor pricing is still the final word.'],
  ['Will It Look Like My Actual Room?','Yes. Every render is built on the photo you upload, so the walls, windows, ceiling height and camera angle stay exactly where they are. Only furniture, finishes, color and lighting change. That is the difference between this and a general purpose image generator, which will happily invent a room that does not exist.'],
  ['What Does Budget Mode Actually Do?','It constrains the generation. Set a Refresh budget and the AI reaches for paint, hardware, lighting and refaced doors. Set a Renovation budget and new cabinets, an island and appliances come into scope. Same photo, same style, genuinely different design, because the money is different. You can also generate the same room at three budget bands and compare what the jump buys.'],
  ['Is The Free Plan Really Usable?','Yes. Your first design needs no account at all, then a free account gives you 5 credits a day. Free includes every space type, the full style library, Reality Lock, the object controls and a typical budget range looked up by room type, finish level and market. That typical range is honest about what it is, since it is not computed from your photo. Output is watermarked at standard resolution. We charge when you need clean files, the scope computed from your own room, the ARV number, batch staging or team tools.'],
  ['What Is The Fair Use Policy?','All plans, add-ons and top-ups include a fair use policy. Sustained usage far beyond the typical pattern for your plan may pause new generations for 24 hours. We will always contact you first.'],
  ['Do You Charge Per Seat?','Pro includes 5 team seats and Studio includes unlimited seats at $35 a month. Add your photographer, assistant, project manager and GC without paying by the head. We meter credits, not people.'],
  ['What Is Founding Member Pricing?','The first 500 accounts lock their rate permanently, including through plan changes, and receive a Renovation Planning Pack worth $49. The counter on the pricing page is an exact count of claimed accounts, not a timer and not a per visitor reset. When it reaches zero the price rises and does not come back down.'],
  ['Can I Use These Images On The MLS?','Yes, on any paid plan, and the disclosure engine handles the compliance side. Most MLSs and several states require virtually staged or digitally altered photos to be labeled. Pick your market once and every export gets the correct label plus a disclosure sheet for your transaction file. Confirm your local rule, since they do change.'],
  ['I Only Have One Kitchen To Do. Do I Need A Subscription?','No. Buy a Single Room Pack at $12 or a Renovation Planning Pack at $49, keep everything you generate, and walk away. A homeowner doing one project should not end up with a monthly bill following them around.'],
  ['Who Owns The Images?','You do. Every paid plan includes a license on everything you generate, commercial from Pro up, and the images stay yours even if you cancel or request a refund.'],
];
