/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as FreeAiInteriorDesignRouteImport } from './routes/free/ai-interior-design'
import { Route as FreeArvCalculatorRouteImport } from './routes/free/arv-calculator'
import { Route as FreeRehabCostCalculatorRouteImport } from './routes/free/rehab-cost-calculator'
import { Route as FreeVirtualStagingRouteImport } from './routes/free/virtual-staging'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PricingCompareRouteImport } from './routes/pricing_.compare'
import { Route as PricingCreditsRouteImport } from './routes/pricing_.credits'
import { Route as ApiPublicFoundingRouteImport } from './routes/api/public/founding'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FreeAiInteriorDesignRoute = FreeAiInteriorDesignRouteImport.update({
  id: '/free/ai-interior-design',
  path: '/free/ai-interior-design',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeArvCalculatorRoute = FreeArvCalculatorRouteImport.update({
  id: '/free/arv-calculator',
  path: '/free/arv-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRehabCostCalculatorRoute = FreeRehabCostCalculatorRouteImport.update({
  id: '/free/rehab-cost-calculator',
  path: '/free/rehab-cost-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeVirtualStagingRoute = FreeVirtualStagingRouteImport.update({
  id: '/free/virtual-staging',
  path: '/free/virtual-staging',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCompareRoute = PricingCompareRouteImport.update({
  id: '/pricing_/compare',
  path: '/pricing/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingCreditsRoute = PricingCreditsRouteImport.update({
  id: '/pricing_/credits',
  path: '/pricing/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFoundingRoute = ApiPublicFoundingRouteImport.update({
  id: '/api/public/founding',
  path: '/api/public/founding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/founders': typeof FoundersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/free/ai-interior-design': typeof FreeAiInteriorDesignRoute
  '/free/arv-calculator': typeof FreeArvCalculatorRoute
  '/free/rehab-cost-calculator': typeof FreeRehabCostCalculatorRoute
  '/free/virtual-staging': typeof FreeVirtualStagingRoute
  '/p/$token': typeof PTokenRoute
  '/pricing/compare': typeof PricingCompareRoute
  '/pricing/credits': typeof PricingCreditsRoute
  '/api/public/founding': typeof ApiPublicFoundingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/founders': typeof FoundersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/free/ai-interior-design': typeof FreeAiInteriorDesignRoute
  '/free/arv-calculator': typeof FreeArvCalculatorRoute
  '/free/rehab-cost-calculator': typeof FreeRehabCostCalculatorRoute
  '/free/virtual-staging': typeof FreeVirtualStagingRoute
  '/p/$token': typeof PTokenRoute
  '/pricing/compare': typeof PricingCompareRoute
  '/pricing/credits': typeof PricingCreditsRoute
  '/api/public/founding': typeof ApiPublicFoundingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/founders': typeof FoundersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/free/ai-interior-design': typeof FreeAiInteriorDesignRoute
  '/free/arv-calculator': typeof FreeArvCalculatorRoute
  '/free/rehab-cost-calculator': typeof FreeRehabCostCalculatorRoute
  '/free/virtual-staging': typeof FreeVirtualStagingRoute
  '/p/$token': typeof PTokenRoute
  '/pricing_/compare': typeof PricingCompareRoute
  '/pricing_/credits': typeof PricingCreditsRoute
  '/api/public/founding': typeof ApiPublicFoundingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/founders'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/free/ai-interior-design'
    | '/free/arv-calculator'
    | '/free/rehab-cost-calculator'
    | '/free/virtual-staging'
    | '/p/$token'
    | '/pricing/compare'
    | '/pricing/credits'
    | '/api/public/founding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/founders'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/free/ai-interior-design'
    | '/free/arv-calculator'
    | '/free/rehab-cost-calculator'
    | '/free/virtual-staging'
    | '/p/$token'
    | '/pricing/compare'
    | '/pricing/credits'
    | '/api/public/founding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/founders'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/app'
    | '/free/ai-interior-design'
    | '/free/arv-calculator'
    | '/free/rehab-cost-calculator'
    | '/free/virtual-staging'
    | '/p/$token'
    | '/pricing_/compare'
    | '/pricing_/credits'
    | '/api/public/founding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  FoundersRoute: typeof FoundersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  FreeAiInteriorDesignRoute: typeof FreeAiInteriorDesignRoute
  FreeArvCalculatorRoute: typeof FreeArvCalculatorRoute
  FreeRehabCostCalculatorRoute: typeof FreeRehabCostCalculatorRoute
  FreeVirtualStagingRoute: typeof FreeVirtualStagingRoute
  PTokenRoute: typeof PTokenRoute
  PricingCompareRoute: typeof PricingCompareRoute
  PricingCreditsRoute: typeof PricingCreditsRoute
  ApiPublicFoundingRoute: typeof ApiPublicFoundingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/free/ai-interior-design': {
      id: '/free/ai-interior-design'
      path: '/free/ai-interior-design'
      fullPath: '/free/ai-interior-design'
      preLoaderRoute: typeof FreeAiInteriorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free/arv-calculator': {
      id: '/free/arv-calculator'
      path: '/free/arv-calculator'
      fullPath: '/free/arv-calculator'
      preLoaderRoute: typeof FreeArvCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free/rehab-cost-calculator': {
      id: '/free/rehab-cost-calculator'
      path: '/free/rehab-cost-calculator'
      fullPath: '/free/rehab-cost-calculator'
      preLoaderRoute: typeof FreeRehabCostCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free/virtual-staging': {
      id: '/free/virtual-staging'
      path: '/free/virtual-staging'
      fullPath: '/free/virtual-staging'
      preLoaderRoute: typeof FreeVirtualStagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing_/compare': {
      id: '/pricing_/compare'
      path: '/pricing/compare'
      fullPath: '/pricing/compare'
      preLoaderRoute: typeof PricingCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing_/credits': {
      id: '/pricing_/credits'
      path: '/pricing/credits'
      fullPath: '/pricing/credits'
      preLoaderRoute: typeof PricingCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/founding': {
      id: '/api/public/founding'
      path: '/api/public/founding'
      fullPath: '/api/public/founding'
      preLoaderRoute: typeof ApiPublicFoundingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  FoundersRoute: FoundersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  FreeAiInteriorDesignRoute: FreeAiInteriorDesignRoute,
  FreeArvCalculatorRoute: FreeArvCalculatorRoute,
  FreeRehabCostCalculatorRoute: FreeRehabCostCalculatorRoute,
  FreeVirtualStagingRoute: FreeVirtualStagingRoute,
  PTokenRoute: PTokenRoute,
  PricingCompareRoute: PricingCompareRoute,
  PricingCreditsRoute: PricingCreditsRoute,
  ApiPublicFoundingRoute: ApiPublicFoundingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
